
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Reddah.Web.UI
{

using System;
    using System.Collections.Generic;
    
public partial class Rank
{

    public int Id { get; set; }

    public string AppId { get; set; }

    public string Sub { get; set; }

    public string UserName { get; set; }

    public int Score { get; set; }

    public System.DateTime CreatedOn { get; set; }

}

}
