
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Reddah.Web.UI
{

using System;
    using System.Collections.Generic;
    
public partial class UserFriend
{

    public int Id { get; set; }

    public string UserName { get; set; }

    public string Watch { get; set; }

    public string Just { get; set; }

    public Nullable<System.DateTime> RequestOn { get; set; }

    public Nullable<int> Approve { get; set; }

    public string NoteName { get; set; }

}

}
