//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reddah.Web.UI.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reddah.Web.UI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Account
        /// </summary>
        public static string Header_MyAccount
        {
            get
            {
                return ResourceManager.GetString("Header_MyAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Join Now
        /// </summary>
        public static string Header_JoinNow
        {
            get
            {
                return ResourceManager.GetString("Header_JoinNow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign In
        /// </summary>
        public static string Header_SignIn
        {
            get
            {
                return ResourceManager.GetString("Header_SignIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home
        /// </summary>
        public static string Navi_Home
        {
            get
            {
                return ResourceManager.GetString("Navi_Home", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Assistance
        /// </summary>
        public static string Assistance_Title
        {
            get
            {
                return ResourceManager.GetString("Assistance_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Top Issues in Browse page
        /// </summary>
        public static string Browse_TopIssues
        {
            get
            {
                return ResourceManager.GetString("Browse_TopIssues", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show More in Browse page
        /// </summary>
        public static string Browse_ShowMoreText
        {
            get
            {
                return ResourceManager.GetString("Browse_ShowMoreText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show Less in Browse page
        /// </summary>
        public static string Browse_ShowLessText
        {
            get
            {
                return ResourceManager.GetString("Browse_ShowLessText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to United States for change locale in the footer
        /// </summary>
        public static string Footer_ChangeLocale
        {
            get
            {
                return ResourceManager.GetString("Footer_ChangeLocale", resourceCulture);
            }
        }

        public static string Header_Create
        {
            get
            {
                return ResourceManager.GetString("Header_Create", resourceCulture);
            }
        }
    }
}
