//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reddah.Web.UI.Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reddah.Web.UI.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to My Account
        /// </summary>
        public static string Header_MyAccount
        {
            get
            {
                return ResourceManager.GetString("Header_MyAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Join Now
        /// </summary>
        public static string Header_JoinNow
        {
            get
            {
                return ResourceManager.GetString("Header_JoinNow", resourceCulture);
            }
        }

        public static string Header_SignIn
        {
            get
            {
                return ResourceManager.GetString("Header_SignIn", resourceCulture);
            }
        }

        public static string Header_SignOut
        {
            get
            {
                return ResourceManager.GetString("Header_SignOut", resourceCulture);
            }
        }

        public static string Header_Want
        {
            get
            {
                return ResourceManager.GetString("Header_Want", resourceCulture);
            }
        }

        public static string Header_Or
        {
            get
            {
                return ResourceManager.GetString("Header_Or", resourceCulture);
            }
        }
        public static string Header_InSeconds
        {
            get
            {
                return ResourceManager.GetString("Header_InSeconds", resourceCulture);
            }
        }

        public static string Navi_Home
        {
            get
            {
                return ResourceManager.GetString("Navi_Home", resourceCulture);
            }
        }

        public static string Assistance_Title
        {
            get
            {
                return ResourceManager.GetString("Assistance_Title", resourceCulture);
            }
        }

        public static string Browse_TopIssues
        {
            get
            {
                return ResourceManager.GetString("Browse_TopIssues", resourceCulture);
            }
        }

        public static string Browse_ShowMoreText
        {
            get
            {
                return ResourceManager.GetString("Browse_ShowMoreText", resourceCulture);
            }
        }

        public static string Browse_ShowLessText
        {
            get
            {
                return ResourceManager.GetString("Browse_ShowLessText", resourceCulture);
            }
        }

        public static string Footer_ChangeLocale
        {
            get
            {
                return ResourceManager.GetString("Footer_ChangeLocale", resourceCulture);
            }
        }

        public static string ChangeLocale_Title
        {
            get
            {
                return ResourceManager.GetString("ChangeLocale_Title", resourceCulture);
            }
        }

        public static string ChangeLocale_Desc
        {
            get
            {
                return ResourceManager.GetString("ChangeLocale_Desc", resourceCulture);
            }
        }

        public static string Header_Create
        {
            get
            {
                return ResourceManager.GetString("Header_Create", resourceCulture);
            }
        }

        public static string Menu_Controversial
        {
            get
            {
                return ResourceManager.GetString("Menu_Controversial", resourceCulture);
            }
        }

        public static string Menu_Gilded
        {
            get
            {
                return ResourceManager.GetString("Menu_Gilded", resourceCulture);
            }
        }

        public static string Menu_Hot
        {
            get
            {
                return ResourceManager.GetString("Menu_Hot", resourceCulture);
            }
        }

        public static string Menu_New
        {
            get
            {
                return ResourceManager.GetString("Menu_New", resourceCulture);
            }
        }

        public static string Menu_Promoted
        {
            get
            {
                return ResourceManager.GetString("Menu_Promoted", resourceCulture);
            }
        }

        public static string Menu_Rising
        {
            get
            {
                return ResourceManager.GetString("Menu_Rising", resourceCulture);
            }
        }

        public static string Menu_Games
        {
            get
            {
                return ResourceManager.GetString("Menu_Games", resourceCulture);
            }
        }

        public static string Menu_Download
        {
            get
            {
                return ResourceManager.GetString("Menu_Download", resourceCulture);
            }
        }

        public static string Menu_Support
        {
            get
            {
                return ResourceManager.GetString("Menu_Support", resourceCulture);
            }
        }

        public static string Menu_Search
        {
            get
            {
                return ResourceManager.GetString("Menu_Search", resourceCulture);
            }
        }

        public static string Menu_Top
        {
            get
            {
                return ResourceManager.GetString("Menu_Top", resourceCulture);
            }
        }

        public static string Right_Feedbacks
        {
            get
            {
                return ResourceManager.GetString("Right_Feedbacks", resourceCulture);
            }
        }

        public static string Right_DiscussAd
        {
            get
            {
                return ResourceManager.GetString("Right_DiscussAd", resourceCulture);
            }
        }

        public static string Right_ContactUs
        {
            get
            {
                return ResourceManager.GetString("Right_ContactUs", resourceCulture);
            }
        }

        public static string Right_Feedbacks_Desc
        {
            get
            {
                return ResourceManager.GetString("Right_Feedbacks_Desc", resourceCulture);
            }
        }

        public static string Right_DiscussAd_Desc
        {
            get
            {
                return ResourceManager.GetString("Right_DiscussAd_Desc", resourceCulture);
            }
        }

        public static string Right_ContactUs_Desc
        {
            get
            {
                return ResourceManager.GetString("Right_ContactUs_Desc", resourceCulture);
            }
        }

        public static string Right_Tags
        {
            get
            {
                return ResourceManager.GetString("Right_Tags", resourceCulture);
            }
        }

        public static string Article_TrendingSubReddah
        {
            get
            {
                return ResourceManager.GetString("Article_TrendingSubReddah", resourceCulture);
            }
        }

        public static string Article_Comments
        {
            get
            {
                return ResourceManager.GetString("Article_Comments", resourceCulture);
            }
        }

        public static string Article_WhatThis
        {
            get
            {
                return ResourceManager.GetString("Article_WhatThis", resourceCulture);
            }
        }

        public static string Article_WhatThisTip
        {
            get
            {
                return ResourceManager.GetString("Article_WhatThisTip", resourceCulture);
            }
        }

        public static string Article_More
        {
            get
            {
                return ResourceManager.GetString("Article_More", resourceCulture);
            }
        }

        public static string Article_Prev
        {
            get
            {
                return ResourceManager.GetString("Article_Prev", resourceCulture);
            }
        }

        public static string Article_Next
        {
            get
            {
                return ResourceManager.GetString("Article_Next", resourceCulture);
            }
        }

        public static string Article_OrTry
        {
            get
            {
                return ResourceManager.GetString("Article_OrTry", resourceCulture);
            }
        }

        public static string Article_RandomSubReddah
        {
            get
            {
                return ResourceManager.GetString("Article_RandomSubReddah", resourceCulture);
            }
        }

        public static string Article_Likeit
        {
            get
            {
                return ResourceManager.GetString("Article_Likeit", resourceCulture);
            }
        }

        public static string Article_Share
        {
            get
            {
                return ResourceManager.GetString("Article_Share", resourceCulture);
            }
        }

        public static string Article_CommentTitle
        {
            get
            {
                return ResourceManager.GetString("Article_CommentTitle", resourceCulture);
            }
        }

        public static string Article_CommentCount
        {
            get
            {
                return ResourceManager.GetString("Article_CommentCount", resourceCulture);
            }
        }

        public static string Article_Mapping
        {
            get
            {
                return ResourceManager.GetString("Article_Mapping", resourceCulture);
            }
        }

        public static string Login_UserName
        {
            get
            {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }

        public static string Login_Password
        {
            get
            {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }

        public static string Login_ConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("Login_ConfirmPassword", resourceCulture);
            }
        }

        public static string Login_Email
        {
            get
            {
                return ResourceManager.GetString("Login_Email", resourceCulture);
            }
        }

        public static string Login_RememberMe
        {
            get
            {
                return ResourceManager.GetString("Login_RememberMe", resourceCulture);
            }
        }

        public static string Login_Signup
        {
            get
            {
                return ResourceManager.GetString("Login_Signup", resourceCulture);
            }
        }

        public static string Login_CreateNewAccount
        {
            get
            {
                return ResourceManager.GetString("Login_CreateNewAccount", resourceCulture);
            }
        }

        public static string Footer_TermsOfUse
        {
            get
            {
                return ResourceManager.GetString("Footer_TermsOfUse", resourceCulture);
            }
        }

        public static string Footer_PrivacyStatement
        {
            get
            {
                return ResourceManager.GetString("Footer_PrivacyStatement", resourceCulture);
            }
        }

        public static string Footer_ContentPolicy
        {
            get
            {
                return ResourceManager.GetString("Footer_ContentPolicy", resourceCulture);
            }
        }

        public static string Footer_Press
        {
            get
            {
                return ResourceManager.GetString("Footer_Press", resourceCulture);
            }
        }

        public static string Footer_Jobs
        {
            get
            {
                return ResourceManager.GetString("Footer_Jobs", resourceCulture);
            }
        }

        public static string Footer_ForDevelopers
        {
            get
            {
                return ResourceManager.GetString("Footer_ForDevelopers", resourceCulture);
            }
        }

        public static string Login_AgreeWord
        {
            get
            {
                return ResourceManager.GetString("Login_AgreeWord", resourceCulture);
            }
        }

        public static string Login_ReadWord
        {
            get
            {
                return ResourceManager.GetString("Login_ReadWord", resourceCulture);
            }
        }

        public static string Login_And
        {
            get
            {
                return ResourceManager.GetString("Login_And", resourceCulture);
            }
        }

        public static string Login_Msg_WrongPW
        {
            get
            {
                return ResourceManager.GetString("Login_Msg_WrongPW", resourceCulture);
            }
        }

        public static string Login_Msg_UserNameRequire
        {
            get
            {
                return ResourceManager.GetString("Login_Msg_UserNameRequire", resourceCulture);
            }
        }

        public static string Login_Msg_PasswordRequire
        {
            get
            {
                return ResourceManager.GetString("Login_Msg_PasswordRequire", resourceCulture);
            }
        }

        public static string Login_Msg_EmailRequire
        {
            get
            {
                return ResourceManager.GetString("Login_Msg_EmailRequire", resourceCulture);
            }
        }

        public static string Msg_Deleted
        {
            get
            {
                return ResourceManager.GetString("Msg_Deleted", resourceCulture);
            }
        }

        public static string Submit_PageTitle_New
        {
            get
            {
                return ResourceManager.GetString("Submit_PageTitle_New", resourceCulture);
            }
        }

        public static string Submit_PageTitle_Edit
        {
            get
            {
                return ResourceManager.GetString("Submit_PageTitle_Edit", resourceCulture);
            }
        }

        public static string Submit_PageDesc
        {
            get
            {
                return ResourceManager.GetString("Submit_PageDesc", resourceCulture);
            }
        }

        public static string Submit_Title
        {
            get
            {
                return ResourceManager.GetString("Submit_Title", resourceCulture);
            }
        }

        public static string Submit_Group
        {
            get
            {
                return ResourceManager.GetString("Submit_Group", resourceCulture);
            }
        }

        public static string Submit_Abstract
        {
            get
            {
                return ResourceManager.GetString("Submit_Abstract", resourceCulture);
            }
        }

        public static string Submit_Captura_New
        {
            get
            {
                return ResourceManager.GetString("Submit_Captura_New", resourceCulture);
            }
        }

        public static string Submit_Captura_Robot
        {
            get
            {
                return ResourceManager.GetString("Submit_Captura_Robot", resourceCulture);
            }
        }

        public static string Submit_Button_Submit
        {
            get
            {
                return ResourceManager.GetString("Submit_Button_Submit", resourceCulture);
            }
        }

        public static string Submit_Button_Cancel
        {
            get
            {
                return ResourceManager.GetString("Submit_Button_Cancel", resourceCulture);
            }
        }

        public static string Submit_Button_Login_New
        {
            get
            {
                return ResourceManager.GetString("Submit_Button_Login_New", resourceCulture);
            }
        }

        public static string Submit_Button_Login_Edit
        {
            get
            {
                return ResourceManager.GetString("Submit_Button_Login_Edit", resourceCulture);
            }
        }

        public static string Error_No_More_Result
        {
            get
            {
                return ResourceManager.GetString("Error_No_More_Result", resourceCulture);
            }
        }

        public static string Error_Server_Error
        {
            get
            {
                return ResourceManager.GetString("Error_Server_Error", resourceCulture);
            }
        }

        public static string List_Submit
        {
            get
            {
                return ResourceManager.GetString("List_Submit", resourceCulture);
            }
        }

        public static string List_By
        {
            get
            {
                return ResourceManager.GetString("List_By", resourceCulture);
            }
        }

        public static string List_Time_Format
        {
            get
            {
                return ResourceManager.GetString("List_Time_Format", resourceCulture);
            }
        }

        public static string List_Time_Just
        {
            get
            {
                return ResourceManager.GetString("List_Time_Just", resourceCulture);
            }
        }

        public static string List_Time_Year
        {
            get
            {
                return ResourceManager.GetString("List_Time_Year", resourceCulture);
            }
        }

        public static string List_Time_Month
        {
            get
            {
                return ResourceManager.GetString("List_Time_Month", resourceCulture);
            }
        }

        public static string List_Time_Day
        {
            get
            {
                return ResourceManager.GetString("List_Time_Day", resourceCulture);
            }
        }

        public static string List_Time_Hour
        {
            get
            {
                return ResourceManager.GetString("List_Time_Hour", resourceCulture);
            }
        }

        public static string List_Time_Minute
        {
            get
            {
                return ResourceManager.GetString("List_Time_Minute", resourceCulture);
            }
        }

        public static string List_Time_Second
        {
            get
            {
                return ResourceManager.GetString("List_Time_Second", resourceCulture);
            }
        }

        public static string List_Time_Years
        {
            get
            {
                return ResourceManager.GetString("List_Time_Years", resourceCulture);
            }
        }

        public static string List_Time_Months
        {
            get
            {
                return ResourceManager.GetString("List_Time_Months", resourceCulture);
            }
        }

        public static string List_Time_Days
        {
            get
            {
                return ResourceManager.GetString("List_Time_Days", resourceCulture);
            }
        }

        public static string List_Time_Hours
        {
            get
            {
                return ResourceManager.GetString("List_Time_Hours", resourceCulture);
            }
        }

        public static string List_Time_Minutes
        {
            get
            {
                return ResourceManager.GetString("List_Time_Minutes", resourceCulture);
            }
        }

        public static string List_Time_Seconds
        {
            get
            {
                return ResourceManager.GetString("List_Time_Seconds", resourceCulture);
            }
        }

        public static string List_LastUpdateOn
        {
            get
            {
                return ResourceManager.GetString("List_LastUpdateOn", resourceCulture);
            }
        }

        public static string Comment_Reply
        {
            get
            {
                return ResourceManager.GetString("Comment_Reply", resourceCulture);
            }
        }

        public static string Comment_Delete
        {
            get
            {
                return ResourceManager.GetString("Comment_Delete", resourceCulture);
            }
        }

        public static string Comment_Edit
        {
            get
            {
                return ResourceManager.GetString("Comment_Edit", resourceCulture);
            }
        }

        public static string Comment_Hint
        {
            get
            {
                return ResourceManager.GetString("Comment_Hint", resourceCulture);
            }
        }

        public static string Comment_Write
        {
            get
            {
                return ResourceManager.GetString("Comment_Write", resourceCulture);
            }
        }

        public static string Comment_Good
        {
            get
            {
                return ResourceManager.GetString("Comment_Good", resourceCulture);
            }
        }
    }
}
